### ISSUE TITLE
CORS issue preventing adding Staking to Gnosis

### ISSUE THREAD

**Issue by kelonye** [Synthetixio/issues#269]
### Summary
Issue described at https://github.com/Synthetixio/staking/issues/639

### Dev tasks
- [x] Fix manifest.json

### QA tasks
- [ ] [PR](https://github.com/Synthetixio/staking/pull/640)
- [ ] Create a safe on gnosis
- [x] Click "Apps" on the sidebar
- [x] Click "Add custom dapp"
- [x] Paste "https://staking-git-hotfix-cors-synthetixio.vercel.app" in the URL text input.
- [x] Expect the synthetix logo to be loaded in the icon section.
- [x] Click the "This app is not a Gnosis product and I agree to use this app at my own risk." checkbox.
- [x] Expect the "Add" button to be enabled.
- [x] Expect the dapp to be added once the "Add" button is clicked.

**Comment by Rafanator** [comment]
I tried all items on the list except creating a new Safe, as I already had one to test it on. 

Everything seems to work fine, the only issue is that I think we should add change the name to `Synthetix Staking` since it seems a bit generic as it looks now if it only says `Staking`:

![Screenshot 2021-07-26 at 15 41 30](https://user-images.githubusercontent.com/26544214/126999547-43747475-ef97-4bd5-90be-ef840336d322.png)

Wdyt?

**Comment by kelonye** [comment]
Awesome. I've pushed an update 👍🏽

**Comment by andytcf** [comment]
@vbstreetz @gberg1 closing this issue
