### ISSUE TITLE
[CHORE]: Test Solidity V8.X on new contracts

### ISSUE THREAD

**Issue by andytcf** [Synthetixio/issues#357]
### Summary

Test out the new contracts with the latest version of Solidity

**Comment by artdgn** [comment]
1. PR for approach #1 - minimal upgrade of a new contract: https://github.com/Synthetixio/synthetix/pull/1571

2. The more promising approach - upgrade everything: https://github.com/Synthetixio/synthetix/pull/1576

**Comment by artdgn** [comment]
After discussing the tradeoff with @justinjmoses the required effort and risk seems to outweigh the benefits in view of the pending transition to V3. 

## In case we do decide to move to Sol8 (e.g. due to delays on V3):
In case we do decide to transition to 0.8 while still in v2x phase, the work on https://github.com/Synthetixio/synthetix/pull/1576 can be rebased and resumed.

## Main takeaways and lessons for V3 from the work done in https://github.com/Synthetixio/synthetix/pull/1576:
- Composition vs. inheritance: inheriting common base contracts instead of composing with common interfaces should be avoided and reduced if possible. The gas savings of jumps vs. calls should be weighted against the system wide coupling. At some point, the system design costs, outweigh the performance optimisation savings. This is because all contracts are coupled to the common bases, which makes any changes much harder - example - all contracts' solidity versions have to be upgraded together.
- The systems upgradability is limited by its immutable part - in this case the choice of immutable stateful token contracts. This creates a situation with a lot of the upgradability risks, but only some of the benefits. Perhaps another upgradability approach would be better for V3. Example here: not being able to upgrade old contracts to be compatible with new contracts.
- If possible we should rely as much as possible on other tools in our workflow, and remove our own scripts and utilities as soon as comparable tools become available e.g. flattening, verificaiton, compilation for deployment, etc etc. The assumptions built in into the custom scripts break over time, require maintenance, and slow down iteration speed. If we had to switch to V0.8 now, majority of the work would be on adapting our scripts (flattening, verification, building, deployment).
